name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 
    - name: installing deps
      run: | 
        cd ./web
        rustup target add wasm32-unknown-unknown
        cargo install trunk wasm-bindgen-cli
        cd ..
    - name: Build
      run: |
        cd web
        trunk build --release
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: web/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
