[package]
name = "web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tetris = { path = "../tetris" }
web-sys = { version = "0.3.60", features = ["KeyboardEvent"] }
yew = "0.19.3"
